#!/bin/bash

l1=${1:-'1e5'}
l2=${2:-'5e5'}

echo Dx
calc_D.py -f msd_x.txt -l1 $l1 -l2 $l2 -of D_x
echo Dy
calc_D.py -f msd_y.txt -l1 $l1 -l2 $l2 -of D_y
echo Dz
calc_D.py -f msd_z.txt -l1 $l1 -l2 $l2 -of D_z
echo D
calc_D.py -f msd_fft.txt -l1 $l1 -l2 $l2 -of D_H