#!/bin/bash

output_file="TOTEN_output.txt"

if [[ -e $output_file ]]; then
    rm $output_file
fi

for dir in */; do
    if [[ -e "${dir}/OUTCAR" ]]; then
        result=$(tac "${dir}/OUTCAR" | grep -m1 'TOTEN' | awk '{print $(NF-1) " " $NF}')
        echo "${dir%/} $result" >> $output_file
    fi
done
