#!/usr/bin/env python3

import numpy as np
from matplotlib import pyplot as plt
import lammps_logfile
from matplotlib import rcParams
import argparse

rcParams['font.size'] = '16'
rcParams['xtick.direction'] = 'in'
rcParams['ytick.direction'] = 'in'

parser = argparse.ArgumentParser(description="Plot contents from lammps log files")
parser.add_argument("-i", "--input_file", type=str, default="log.lammps",  help="LAMMPS output file")
parser.add_argument("-o", "--out_figure",type=str,default='props.jpg', help="Out figure name")
parser.add_argument("-n", "--step_number",type=int,default=10000, help="Plot every this number of time steps")
args = parser.parse_args()

log = lammps_logfile.File(args.input_file)
f = args.out_figure
n = args.step_number

fig, ax = plt.subplots(4,1,figsize=(12,20),sharex=True)
fig.subplots_adjust(hspace=0.10)

for index, i in enumerate(["Temp", "Press", "PotEng", "TotEng"]):
    x = log.get("Step")
    y = log.get(i)
    if i == "Press":
        y /= 1e4
    avgy = np.mean(y)
    ax[index].plot(x[::n], y[::n])
    ax[index].axhline(avgy, c = 'k', ls = '--', alpha = 0.7)
    ax[index].set_title(i + ' = ' + "%.2f" % (avgy))
    ax[index].set_ylabel(i)

ax[3].set_xlabel('Step')

plt.savefig(f, dpi=300, bbox_inches='tight')