#!/bin/bash

if [ -z $1 ]; then
    echo Missing parameters
    exit 1
fi

mkdump.py -t $1
mv brg.dump nvt
cd nvt
atomsk brg.dump nvt.lmp
sed -i '13c 1   24.30500000             # Mg' nvt.lmp
sed -i '14c 2   28.08500000             # Si' nvt.lmp
sed -i '15c 3   15.99900000             # O' nvt.lmp
sed -i '16c 4   1.00800000              # H' nvt.lmp
