#!/bin/bash

if [ -z $2 ]; then
    echo Missing parameters
    exit 1
fi
mkdir nvt
cd nvt

cat ../../t2kp25/nvt/in.lammps | sed -e "s/T equal 2000.0/T equal ${1}000.0/g" -e "s/P equal 250000/P equal ${2}0000/g" > ./in.lammps
cat ../../t2kp25/nvt/run.slurm | sed -e "s/name=t2kp25/name=t${1}kp${2}/g" > ./run.slurm
