#!/bin/bash

if [ -z $3 ]; then
    echo Missing parameters
    exit 1
fi

cp ../_inputs/npt/in.lammps .
cp ../_inputs/npt/run.slurm .

atomsk conf.lmp -duplicate $1 $2 $3 npt.lmp

sed -i 's/1   1.00800000              # H/1   24.30500000             # Mg/g' npt.lmp
sed -i 's/2   4.00260200              # He/2   28.08500000             # Si/g' npt.lmp
sed -i 's/3   6.94000000              # Li/3   15.99900000             # O/g' npt.lmp
sed -i 's/4   9.01218200              # Be/4   1.00800000              # H/g' npt.lmp