#!/bin/bash

start_step=${1:-'20000'}
mode=${2:-'aniso'}

if test -e ./log.lammps
then
    echo log.lammps found!
else
    echo log.lammps not found!
    exit 1
fi

if test -e ./BEST_STEP
then
    echo Double run!
    exit 1
fi

find_best_frame -st $start_step -$mode

if test -e ./BEST_STEP
then
    echo Best step found!
else
    echo Best step not found!
    exit 1
fi

beststep=$(cat BEST_STEP)

mkdir nvt

extract_dump_frame -i npt.dump -t $beststep
mv selected.dump nvt/
# cp ../_inputs/nvt/in.lammps nvt/
# cp ../_inputs/nvt/run.slurm nvt/

cd nvt
mkdir restart
atomsk selected.dump nvt.lmp
sed -i 's/1   1.00800000              # H/1   24.30500000             # Mg/g' nvt.lmp
sed -i 's/2   4.00260200              # He/2   15.99900000             # O/g' nvt.lmp
sed -i 's/3   6.94000000              # Li/3   55.84500000             # Fe/g' nvt.lmp
sed -i 's/4   9.01218200              # Be/4   183.84000000            # W/g' nvt.lmp

#sbatch run.slurm
