#!/bin/bash

if [ -z $2 ]; then
    echo Missing parameters
    exit 1
fi
mkdir nvt
cd nvt

cat /projects/JIEDENG/yhpeng/diffusion/ppv/nvt/in.lammps | sed -e "s/T equal 2000.0/T equal ${1}000.0/g" > ./in.lammps
cat /projects/JIEDENG/yhpeng/diffusion/ppv/nvt/run.slurm | sed -e "s/name=t2kp140/name=t${1}kd${2}/g" > ./run.slurm

cd ..
mklmp ${1} 140