#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse

parser = argparse.ArgumentParser(description="Extract frames from LAMMPS dump file.")
parser.add_argument("--input_filename", "-i", type=str, default='nvt.dump', help="Input filename (default: nvt.dump)")
parser.add_argument("--output_filename", "-o", type=str, default='extracted.dump', help="Output filename (default: extracted.dump)")
parser.add_argument("--beginstep", "-tb", type=int, help="Target begin frame")
parser.add_argument("--endstep", "-te", type=int, help="Target end frame")

args = parser.parse_args()
t_begin, t_end = args.beginstep, args.endstep

datain = open(args.input_filename, 'r')
dataout = open(args.output_filename, 'w')

# Find and record the target frames
line = datain.readline()
write_flag = False

while line:
    if "ITEM: TIMESTEP" in line:
        timestep_line = datain.readline()
        thisframe = int(timestep_line.strip())
        
        # Check if current frame is within the desired range
        if t_begin <= thisframe <= t_end:
            write_flag = True
            dataout.write("ITEM: TIMESTEP\n")
            dataout.write(timestep_line)
        elif thisframe > t_end:
            break
    elif write_flag:
        dataout.write(line)
    
    line = datain.readline()

datain.close()
dataout.close()
