#!/bin/bash

if [ -z $3 ]; then
    echo Missing parameters
    exit 1
fi

cp -r ./input/ ./${1}-${2}-${3}/
cd ${1}-${2}-${3}/
cp ../input/run.slurm ./run.slurm
sed -i "s/job-name=1-1-1/job-name=${1}-${2}-${3}/g" ./run.slurm
sed -i "s/nodes=1/nodes=${1}/g" ./run.slurm
sed -i "s/ntasks-per-node=1/ntasks-per-node=${2}/g" ./run.slurm
sed -i "s/cpus-per-task=1/cpus-per-task=${3}/g" ./run.slurm
# sed -i "s/OMP_NUM_THREADS=1/OMP_NUM_THREADS=${4}/g" ./run.slurm
# sed -i "s/TF_INTRA_OP_PARALLELISM_THREADS=1/TF_INTRA_OP_PARALLELISM_THREADS=${4}/g" ./run.slurm
# sed -i "s/TF_INTER_OP_PARALLELISM_THREADS=1/TF_INTER_OP_PARALLELISM_THREADS=${5}/g" ./run.slurm
sbatch run.slurm