#!/bin/bash

if [[ $1 == "-iso" ]]; then
  l=$(head -n 1 L.dat)
else
  lx=$(head -n 1 L.dat)
  ly=$(head -n 2 L.dat | tail -n 1)
  lz=$(tail -n 1 L.dat)
fi

mkdir nvt

cp CONTCAR nvt/POSCAR

sed -i '/Lattice velocities and vectors/Q' nvt/POSCAR

if [[ $1 == "-iso" ]]; then
  new_matrix=$(printf "%0.6f 0.000000 0.000000\n0.000000 %0.6f 0.000000\n0.000000 0.000000 %0.6f\n" $l $l $l)
else
  new_matrix=$(printf "%0.6f 0.000000 0.000000\n0.000000 %0.6f 0.000000\n0.000000 0.000000 %0.6f\n" $lx $ly $lz)
fi

{
  head -n 2 nvt/POSCAR
  echo "$new_matrix"
  tail -n +6 nvt/POSCAR
} > nvt/POSCAR.tmp && mv nvt/POSCAR.tmp nvt/POSCAR
