#!/bin/bash

if [[ $1 == "-iso" ]]; then
  l=$(head -n 1 L.dat)
else
  lx=$(head -n 1 L.dat)
  ly=$(head -n 2 L.dat | tail -n 1)
  lz=$(tail -n 1 L.dat)
fi

mkdir nvt
cd nvt

cp ../CONTCAR POSCAR
cp ../POSCAR POSCAR.orig

sed -i '/Lattice velocities and vectors/Q' POSCAR

if [[ $1 == "-iso" ]]; then
  new_matrix=$(printf "%0.6f 0.000000 0.000000\n0.000000 %0.6f 0.000000\n0.000000 0.000000 %0.6f\n" $l $l $l)
else
  new_matrix=$(printf "%0.6f 0.000000 0.000000\n0.000000 %0.6f 0.000000\n0.000000 0.000000 %0.6f\n" $lx $ly $lz)
fi

{
  head -n 2 POSCAR
  echo "$new_matrix"
  if [[ $1 == "-restart" ]]; then
    tail -n +6 POSCAR.orig
  else
    tail -n +6 POSCAR
  fi
} > POSCAR.tmp && mv POSCAR.tmp POSCAR

rm POSCAR.orig
