#!/bin/bash

# mkdir nvt

l=$(head -n 1 L.dat)

cp CONTCAR nvt/POSCAR

sed -i '/Lattice velocities and vectors/Q' nvt/POSCAR

new_matrix=$(printf "%0.4f 0.0000 0.0000\n0.0000 %0.4f 0.0000\n0.0000 0.0000 %0.4f\n" $l $l $l)

{
  head -n 2 nvt/POSCAR
  echo "$new_matrix"
  tail -n +6 nvt/POSCAR
} > nvt/POSCAR.tmp && mv nvt/POSCAR.tmp nvt/POSCAR